<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <RootNamespace>BlazorDrawFBP.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorDrawFBP.csproj" />
  </ItemGroup>
</Project>
