<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Tomlyn" Version="2.10.1" />
    <PackageVersion Include="Z.Blazor.Diagrams" Version="3.0.4.1" />
    <PackageVersion Include="Z.Blazor.Diagrams.Algorithms" Version="3.0.4.1" />
    <PackageVersion Include="Z.Blazor.Diagrams.Core" Version="3.0.4.1" />
  </ItemGroup>
</Project>