name: Release FBP Flow Tool UI
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    if: ${{ !github.event.repository.fork }}
    name: Trigger release-please and docker image creation on release
    uses: dakispro/.github/.github/workflows/release.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
